import { AfterViewInit, ElementRef, EventEmitter, OnDestroy, Renderer2 } from '@angular/core';
import { DomRenderer } from '../common/dom';
import { ControlValueAccessor } from '@angular/forms';
export declare class ColorpickerComponent implements ControlValueAccessor, AfterViewInit, OnDestroy {
    domRenderer: DomRenderer;
    renderer2: Renderer2;
    visible: boolean;
    inline: boolean;
    clickable: boolean;
    pickerAreaViewChild: ElementRef;
    colorPickerViewChild: ElementRef;
    hueAreaViewChild: ElementRef;
    huePickerViewChild: ElementRef;
    pickerViewChild: ElementRef;
    onChange: EventEmitter<any>;
    onClick: EventEmitter<any>;
    colorInput: boolean;
    value: string;
    documentTouchmoveListener: any;
    documentTouchendListener: any;
    documentClickListener: any;
    pickerClickListener: any;
    hueClickListener: any;
    pickerArea: HTMLDivElement;
    colorPicker: HTMLDivElement;
    hueArea: HTMLDivElement;
    huePicker: HTMLDivElement;
    picker: HTMLDivElement;
    touch: any;
    picker_mode: string;
    color: any;
    colorValue: string;
    isDown: boolean;
    topic: string;
    selfClick: boolean;
    pickerDragging: boolean;
    hueDragging: boolean;
    onModelChange: Function;
    onTouchedChange: Function;
    constructor(domRenderer: DomRenderer, renderer2: Renderer2);
    ngAfterViewInit(): void;
    writeValue(value: any): void;
    registerOnChange(fn: Function): void;
    registerOnTouched(fn: Function): void;
    onBlockClick(event: any): void;
    areaClick(event: any): void;
    update(event: any): void;
    createPickingArea(): void;
    createHueArea(): void;
    updateColor(e: any): void;
    updateHueSlider(e: any): void;
    setColor(color: any): void;
    updateHuePicker(): void;
    updatePickerPosition(): void;
    updatePickerBackground(): void;
    setHue(value: any): void;
    updateSliderPosition(elem: any, pos: any): void;
    updatePreviewColor(): void;
    HEXToRGBA(value: string): void;
    changeHexa(value: string): void;
    bindDocumentTouchmoveListener(): void;
    bindDocumentTouchendListener(): void;
    unbindDocumentTouchmoveListener(): void;
    unbindDocumentTouchendListener(): void;
    ngOnDestroy(): void;
}
export declare class ColorPickerModule {
}
