import { Renderer2 } from '@angular/core';
export declare class DomRenderer {
    renderer2: Renderer2;
    static zIndex: number;
    constructor(renderer2: Renderer2);
    addClass(elem: any, className: any): void;
    hasClass(elem: any, className: any): boolean;
    removeClass(elem: any, className: any): void;
    getHiddenElementOuterHeight(elem: any): any;
    getHiddenElementClient(parent: any, elem: any, property: any): number;
    addPrefix(element: any, attr: any, value: any): void;
    toggleFullScreen(elem?: any): void;
    getStyle(elem: any, attr: any): any;
    getRandom(max: any, min: any): number;
    getWebType(): string;
    getRect(elem: any): any;
    fadeIn(element: any, duration: number): void;
    fadeOut(element: any, ms: any): void;
    css(elem: any, style: any): void;
    animationEnd(elem: any, handler: any): void;
    setTransform(element: any, animation: any): void;
    setTransitionDuration(element: any, times: any): void;
    transitionStart(elem: any, handler: any): void;
    transitionEnd(elem: any, handler: any): void;
    deleteTransitionEnd(elem: any, handler: any): void;
    checkPlatform(): any;
    isIE(): boolean;
    listen(elem: any, type: any, handler: any): void;
    parentNode(elem: any): HTMLElement;
    createElement(elem: any): HTMLElement;
    appendChild(parent: any, newDom: any): void;
    insertBefore(parent: any, newDom: any, oldDom: any): void;
    insertAfter(parent: any, newDom: any, oldChild: any): void;
    removeChild(parent: any, oldChild: any): void;
    getOffsetTop(elem: any): number;
    getOffsetLeft(elem: any): number;
    getTouchEvent(): object;
    setProperty(elem: any, name: string, value: any): void;
    getScrollbarWidth(): number;
    dateFormat(date: any, fmt: string): string;
    forEach(arr: any, callback: Function): void;
    createEvent(type: string, detail?: any): CustomEvent;
    triggerEvent(dom: any, event: any): void;
    parentsUntil(dom: any, parent: any): any[];
    preventDefault(event: any): void;
    stopPropagation(event: any): void;
}
